export const _AUTH_LOGIN = '_AUTH_LOGIN';

export const _AUTH_AUTO_LOGIN = '_AUTH_AUTO_LOGIN';

export const _AUTH_LOGIN_SUCCESS = '_AUTH_LOGIN_SUCCESS';

export const _AUTH_LOGIN_FAIL = '_AUTH_LOGIN_FAIL';

export const _AUTH_RESET_BACKEND_STATUS = '_AUTH_RESET_BACKEND_STATUS';

export const _AUTH_LOGOUT = '_LOG_OUT';

export const _AUTH_LOGOUT_SUCCESS = '_AUTH_LOGOUT_SUCCESS';
