export const _GET_CATEGORIES = '_GET_CATEGORIES';

export const _UPDATE_CATEGORIES = '_UPDATE_CATEGORIES';

export const _PUT_CATEGORIES = '_PUT_CATEGORIES';

export const _CANCEL_EDIT_CATEGORY = '_CANCEL_EDIT_CATEGORY';

export const _EDIT_CATEGORY_SUCCESS = '_EDIT_CATEGORY_SUCCESS';

export const _EDIT_CATEGORY_FAIL = '_EDIT_CATEGORY_FAIL';
