export const _GET_CATEGORIES = '_GET_CATEGORIES';

export const _UPDATE_CATEGORY = '_UPDATE_CATEGORY';

export const _EDIT_CATEGORY = '_EDIT_CATEGORY';

export const _PUT_CATEGORIES = '_PUT_CATEGORIES';

export const _CANCEL_EDIT_CATEGORY = '_CANCEL_EDIT_CATEGORY';

export const _EDIT_CATEGORY_SUCCESS = '_EDIT_CATEGORY_SUCCESS';

export const _EDIT_CATEGORY_FAIL = '_EDIT_CATEGORY_FAIL';

export const _RESET_BACKEND_STATUS = '_RESET_BACKEND_STATUS';
