export const _GET_CATEGORIES = '_GET_CATEGORIES';

export const _UPDATE_CATEGORIES = '_UPDATE_CATEGORIES';

export const _PUT_CATEGORIES = '_PUT_CATEGORIES';

export const _CANCEL_EDIT_CATEGORY = '_CANCEL_EDIT_CATEGORY';
