// global
export const _GLOBAL_FETCH_CONSTANT = '_GLOBAL_FETCH_CONSTANT';

export const _GLOBAL_FETCH_CONSTANT_SUCCEED = '_GLOBAL_FETCH_CONSTANT_SUCCEED';

export const _GLOBAL_FETCH_CONSTANT_FAILED = '_GLOBAL_FETCH_CONSTANT_FAILED';

export const _CUSTOMER__GLOBAL_RESET = '_CUSTOMER__GLOBAL_RESET';

// customer
export const _SAVE_CUSTOMER = '_SAVE_CUSTOMER';

export const _CUSTOMER_SAVE_SUCCESS = '_CUSTOMER_SAVE_SUCCESS';

export const _CUSTOMER_SAVE_FAILED = '_CUSTOMER_SAVE_FAILED';

export const _CUSTOMER_SAVE_RESET_BACKEND_STATUS = '_CUSTOMER_SAVE_RESET_BACKEND_STATUS';

// address

export const _ADDRESS_SAVE_RESET_BACKEND_STATUS = '_ADDRESS_SAVE_RESET_BACKEND_STATUS';

export const _ADDRESS_RESET_STATE = '_ADDRESS_RESET_STATE';

export const _ADDRESS_SAVE = '_ADDRESS_SAVE';

export const _ADDRESS_SAVE_SUCCESS = '_ADDRESS_SAVE_SUCCESS';

export const _ADDRESS_SAVE_FAILED = '_ADDRESS_SAVE_FAILED';

export const _ADDRESS_FETCH_GEO_AUTOCOMPLETE = '_ADDRESS_FETCH_GEO_AUTOCOMPLETE';

export const _ADDRESS_FETCH_GEO_AUTOCOMPLETE_FAILED = '_ADDRESS_FETCH_GEO_AUTOCOMPLETE_FAILED';

export const _ADDRESS_FETCH_GEO_AUTOCOMPLETE_SUCCESS = '_ADDRESS_FETCH_GEO_AUTOCOMPLETE_SUCCESS';

export const _ADDRESS_LIST_FETCH = '_ADDRESS_LIST_FETCH';

export const _ADDRESS_LIST_FETCH_SUCCESS = '_ADDRESS_LIST_FETCH_SUCCESS';

export const _ADDRESS_LIST_FETCH_FAILED = '_ADDRESS_LIST_FETCH_FAILED';
