export const _SAVE_CUSTOMER = '_SAVE_CUSTOMER';

export const _CUSTOMER_SAVE_SUCCESS = '_CUSTOMER_SAVE_SUCCESS';

export const _CUSTOMER_SAVE_FAILED = '_CUSTOMER_SAVE_FAILED';

export const _CUSTOMER_SAVE_RESET_BACKEND_STATUS = '_CUSTOMER_SAVE_RESET_BACKEND_STATUS';
