export const _SUBMIT_ADD_PRODUCT_STEP = '_SUBMIT_ADD_PRODUCT_STEP';

export const _REEDIT_PRODUCT = '_REEDIT_PRODUCT';

export const _RESET_ADD_PRODUCT_STATE = '_RESET_ADD_PRODUCT_STATE';

export const _SAVE_PRODUCT = '_SAVE_PRODUCT';

export const _EDIT_PRODUCT_SUCCESS = '_EDIT_PRODUCT_SUCCESS';

export const _EDIT_PRODUCT_FAIL = '_EDIT_PRODUCT_FAIL';

export const _FETCH_PRODUCT = '_FETCH_PRODUCT';

export const _FETCH_PRODUCT_SUCCESS = '_FETCH_PRODUCT_SUCCESS';

export const _FETCH_PRODUCT_FAIL = '_FETCH_PRODUCT_FAIL';

export const _RESET_LIST_BACKEND_STATUS = '_RESET_LIST_BACKEND_STATUS';

export const _LIST_SELECT_KEYS = '_LIST_SELECT_KEYS';

export const _BULK_UPDATE_PRODUCT = '_BULK_UPDATE_PRODUCT';

export const _BULK_UPDATE_SUCCESS = '_BULK_UPDATE_SUCCESS';

export const _BULK_UPDATE_FAIL = '_BULK_UPDATE_FAIL';

export const _PAGINATION_UPDATE = '_PAGINATION_UPDATE';
