export const _SUBMIT_ADD_PRODUCT_STEP = '_SUBMIT_ADD_PRODUCT_STEP';

export const _REEDIT_PRODUCT = '_REEDIT_PRODUCT';

export const _RESET_ADD_PRODUCT_STATE = '_RESET_ADD_PRODUCT_STATE';

export const _SAVE_PRODUCT = '_SAVE_PRODUCT';

export const _EDIT_PRODUCT_SUCCESS = '_EDIT_PRODUCT_SUCCESS';

export const _EDIT_PRODUCT_FAIL = '_EDIT_PRODUCT_FAIL';
