export const _SUBMIT_ADD_PRODUCT_STEP_ONE = '_SUBMIT_ADD_PRODUCT_STEP_ONE';

export const _SUBMIT_ADD_PRODUCT_STEP_TWO = '_SUBMIT_ADD_PRODUCT_STEP_TWO';

export const _GO_STEP_ADD_PRODUCT = '_GO_STEP_ADD_PRODUCT';
