export const _USER_ADMIN_RESET_STATES = '_USER_ADMIN_RESET_STATES';

export const _USER_ADMIN_UPDATE_STATES = '_USER_ADMIN_UPDATE_STATES';

export const _USER_ADMIN_FETCH_ALL = '_USER_ADMIN_FETCH_ALL';

export const _USER_ADMIN_FETCH_ALL_SUCCESS = '_USER_ADMIN_FETCH_ALL_SUCCESS';

export const _USER_ADMIN_FETCH_ALL_FAILED = '_USER_ADMIN_FETCH_ALL_FAILED';

export const _USER_ADMIN_UPDATE = '_USER_ADMIN_UPDATE';

export const _USER_ADMIN_UPDATE_SUCCESS = '_USER_ADMIN_UPDATE_SUCCESS';

export const _USER_ADMIN_UPDATE_FAILED = '_USER_ADMIN_UPDATE_FAILED';

export const _USER_ADMIN_RESET_BACKEND_STATUS = '_USER_ADMIN_RESET_BACKEND_STATUS';

export const _USER_ADMIN_SWITCH_SUB_TAB = '_USER_ADMIN_SWITCH_SUB_TAB';

export const _USER_ADMIN_PUT_ALL_USERROLES = '_USER_ADMIN_PUT_ALL_USERROLES';

export const _USER_ADMIN_FETCH_ALL_USERROLES = '_USER_ADMIN_FETCH_ALL_USERROLES';

export const _USER_ADMIN_FETCH_ALL_USERROLES_FAILED = '_USER_ADMIN_FETCH_ALL_USERROLES_FAILED';

export const _USER_ADMIN_ATTEMPT_DELETE_USERROLE = '_USER_ADMIN_ATTEMPT_DELETE_USERROLE';

export const _USER_ADMIN_DELETE_USERROLE_SUCCEED = '_USER_ADMIN_DELETE_USERROLE_SUCCEED';

export const _USER_ADMIN_DELETE_USERROLE_FAILD = '_USER_ADMIN_DELETE_USERROLE_FAILD';

export const _USER_ADMIN_SET_TEAM_TAB = '_USER_ADMIN_SET_TEAM_TAB';

export const _USER_ROLE_PUT_ALL_USERACCESSES = '_USER_ROLE_PUT_ALL_USERACCESSES';

export const _USER_ROLE_FETCH_ALL_USERACCESSES = '_USER_ROLE_FETCH_ALL_USERACCESSES';

export const _USER_ROLE_FETCH_ALL_USERACCESSES_FAILED = '_USER_ROLE_FETCH_ALL_USERACCESSES_FAILED';

export const _USER_ROLE_RESET_STATES = '_USER_ROLE_RESET_STATES';

export const _USER_ROLE_UPDATE = '_USER_ROLE_UPDATE';

export const _USER_ROLE_EDIT = '_USER_ROLE_EDIT';

export const _USER_ROLE_UPDATE_SUCCESS = '_USER_ROLE_UPDATE_SUCCESS';

export const _USER_ROLE_UPDATE_FAILED = '_USER_ROLE_UPDATE_FAILED';

export const _USER_ROLE_RESET_BACKEND_STATUS = '_USER_ROLE_RESET_BACKEND_STATUS';

export const _USER_ADMINS_RESET_BACKEND_STATUS = '_USER_ADMINS_RESET_BACKEND_STATUS';
