export const _USER_ADMIN_RESET_STATES = '_USER_ADMIN_RESET_STATES';

export const _USER_ADMIN_UPDATE = '_USER_ADMIN_UPDATE';

export const _USER_ADMIN_UPDATE_SUCCESS = '_USER_ADMIN_UPDATE_SUCCESS';

export const _USER_ADMIN_UPDATE_FAILED = '_USER_ADMIN_UPDATE_FAILED';

export const _USER_ADMIN_RESET_BACKEND_STATUS = '_USER_ADMIN_RESET_BACKEND_STATUS';

export const _USER_ADMIN_PUT_ALL_USERROLES = '_USER_ADMIN_PUT_ALL_USERROLES';

export const _USER_ADMIN_FETCH_ALL_USERROLES = '_USER_ADMIN_FETCH_ALL_USERROLES';

export const _USER_ADMIN_ATTEMPT_DELETE_USERROLE = '_USER_ADMIN_ATTEMPT_DELETE_USERROLE';
